### ISSUE TITLE
Clarify or remove dependency on common module

### ISSUE THREAD

**Issue by tylerwalts** [saz/puppet-dnsmasq#10]
In int.pp and hosts.pp there are references to a common::line define.  If the common module is not present in the environment, the puppet run will fail.  Additionally, there is nothing in the Modulefile, medata.json or README which tell which common module or version that this depends on.  Searching the forge for 'common' module gives a handful of same-named results, so it would help to be explicit.

An issue would be to decide how to best handle this:
1. At minimum, call out in the README which common module has been tested with this dnsmasq module.
2. To enforce dependency, add it with a version in the metadata.json
3. (My personal preference) Remove dependency on common module
    * For my use case I don't need the hosts file management so it would be nice if there were a way to pass in a parameter to just not modify hosts file, then I would never have to pull in the common module.

**Comment by saz** [comment]
Should be resolved in the current master
