### ISSUE TITLE
module uses outdated stdlib

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [saz/puppet-dnsmasq#28]
```json
  "dependencies": [
    {
      "name": "puppetlabs/stdlib",
      "version_requirement": ">=2.0.0 < 5.0.0"
    }
  ]
```
stdlib was released on 22 Aug 2018. It's time to upgrade.

**Comment by mpdude** [comment]
@saz Thank you for maintaining this module!

Do you think you could cut a release containing this change?
